// Campora — Constants: Common Subject Suggestions (CS/Engineering)

export const SUBJECT_SUGGESTIONS = [
  { name: 'Operating Systems', code: 'CS301' },
  { name: 'Database Management Systems', code: 'CS302' },
  { name: 'Computer Networks', code: 'CS303' },
  { name: 'Design & Analysis of Algorithms', code: 'CS304' },
  { name: 'Software Engineering', code: 'CS305' },
  { name: 'Data Structures', code: 'CS201' },
  { name: 'Object Oriented Programming', code: 'CS202' },
  { name: 'Discrete Mathematics', code: 'MA201' },
  { name: 'Theory of Computation', code: 'CS401' },
  { name: 'Compiler Design', code: 'CS402' },
  { name: 'Artificial Intelligence', code: 'CS403' },
  { name: 'Machine Learning', code: 'CS404' },
  { name: 'Computer Architecture', code: 'CS305' },
  { name: 'Digital Logic Design', code: 'CS101' },
  { name: 'Microprocessors', code: 'CS306' },
  { name: 'Web Development', code: 'CS405' },
  { name: 'Mobile Application Development', code: 'CS406' },
  { name: 'Cloud Computing', code: 'CS501' },
  { name: 'Cyber Security', code: 'CS502' },
  { name: 'Data Science', code: 'CS503' },
  { name: 'Internet of Things', code: 'CS504' },
  { name: 'Java Programming', code: 'CS203' },
  { name: 'Python Programming', code: 'CS204' },
  { name: 'C Programming', code: 'CS102' },
  { name: 'Mathematics I', code: 'MA101' },
  { name: 'Mathematics II', code: 'MA102' },
  { name: 'Mathematics III', code: 'MA201' },
  { name: 'Physics', code: 'PH101' },
  { name: 'Chemistry', code: 'CH101' },
  { name: 'English', code: 'HS101' },
  { name: 'Environmental Science', code: 'HS201' },
  { name: 'Engineering Graphics', code: 'ME101' },
  { name: 'Electronics', code: 'EC101' },
  { name: 'Signals & Systems', code: 'EC201' },
  { name: 'Communication Systems', code: 'EC301' },
] as const;
